version: "3.4"

services:
  jenkins:
    image: bdusad/jenkins:latest
    ports:
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:jenkins.s.dnam.dk"
        - "traefik.backend=jenkins-http"
        - "traefik.docker.network=proxy-net"
      resources:
        limits:
          memory: 1g
    networks:
      proxy-net:
      slave-net:

  slave:
    image: bdusad/jenkins-swarm-slave:latest
    command: -master http://jenkins:8080 -username swarm-slave -password devopsjava123 -executors 2
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100m
    networks:
      slave-net:

volumes:
  jenkins-data:

networks:
  proxy-net:
    external:
      name: proxy-net
  slave-net:
